/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Anuj Tripathi Portfolio
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * Saves contact form submission and sends email notification
 * @summary Submit contact form
 */
export const submitContactBodyNameMax = 100;

export const submitContactBodyEmailMax = 255;

export const submitContactBodyMessageMin = 10;
export const submitContactBodyMessageMax = 2000;

export const SubmitContactBody = zod.object({
  name: zod.string().min(1).max(submitContactBodyNameMax),
  email: zod.string().email().max(submitContactBodyEmailMax),
  service: zod.enum([
    "SEO",
    "Social Media Marketing",
    "Branding",
    "Website Marketing",
    "Consultation",
  ]),
  message: zod
    .string()
    .min(submitContactBodyMessageMin)
    .max(submitContactBodyMessageMax),
});
