/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Anuj Tripathi Portfolio
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * Saves contact form submission and sends email notification
 * @summary Submit contact form
 */
export declare const submitContactBodyNameMax = 100;
export declare const submitContactBodyEmailMax = 255;
export declare const submitContactBodyMessageMin = 10;
export declare const submitContactBodyMessageMax = 2000;
export declare const SubmitContactBody: zod.ZodObject<{
    name: zod.ZodString;
    email: zod.ZodString;
    service: zod.ZodEnum<["SEO", "Social Media Marketing", "Branding", "Website Marketing", "Consultation"]>;
    message: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    message: string;
    name: string;
    email: string;
    service: "SEO" | "Social Media Marketing" | "Branding" | "Website Marketing" | "Consultation";
}, {
    message: string;
    name: string;
    email: string;
    service: "SEO" | "Social Media Marketing" | "Branding" | "Website Marketing" | "Consultation";
}>;
//# sourceMappingURL=api.d.ts.map