/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Anuj Tripathi Portfolio
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type ContactInputService =
  (typeof ContactInputService)[keyof typeof ContactInputService];

export const ContactInputService = {
  SEO: "SEO",
  Social_Media_Marketing: "Social Media Marketing",
  Branding: "Branding",
  Website_Marketing: "Website Marketing",
  Consultation: "Consultation",
} as const;

export interface ContactInput {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** @maxLength 255 */
  email: string;
  service: ContactInputService;
  /**
   * @minLength 10
   * @maxLength 2000
   */
  message: string;
}

export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  service: string;
  message: string;
  createdAt: string;
}

export interface ErrorResponse {
  error: string;
}
