/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Anuj Tripathi Portfolio
 * OpenAPI spec version: 0.1.0
 */
import type { ContactInputService } from "./contactInputService";

export interface ContactInput {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** @maxLength 255 */
  email: string;
  service: ContactInputService;
  /**
   * @minLength 10
   * @maxLength 2000
   */
  message: string;
}
