/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Anuj Tripathi Portfolio
 * OpenAPI spec version: 0.1.0
 */
export interface ContactSubmission {
    id: number;
    name: string;
    email: string;
    service: string;
    message: string;
    createdAt: Date;
}
//# sourceMappingURL=contactSubmission.d.ts.map