/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Anuj Tripathi Portfolio
 * OpenAPI spec version: 0.1.0
 */

export type ContactInputService =
  (typeof ContactInputService)[keyof typeof ContactInputService];

export const ContactInputService = {
  SEO: "SEO",
  Social_Media_Marketing: "Social Media Marketing",
  Branding: "Branding",
  Website_Marketing: "Website Marketing",
  Consultation: "Consultation",
} as const;
