/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification for Anuj Tripathi Portfolio
 * OpenAPI spec version: 0.1.0
 */
export type ContactInputService = (typeof ContactInputService)[keyof typeof ContactInputService];
export declare const ContactInputService: {
    readonly SEO: "SEO";
    readonly Social_Media_Marketing: "Social Media Marketing";
    readonly Branding: "Branding";
    readonly Website_Marketing: "Website Marketing";
    readonly Consultation: "Consultation";
};
//# sourceMappingURL=contactInputService.d.ts.map